version: '3.1'

services: 
  erpfake-gateway:
    image: erpfake/gateway:1.0.0
    container_name: erpfake-gateway
    environment:
      EUREKA_HOST: "erpfake-eureka"
    ports: 
      - 8082:8082
    networks:
      - erpfake
networks:
  erpfake:
    external:
      name: erpfake-network
