version: '3.6'

services: 
  erpfake-purhcase:
    image: erpfake/purchase:1.0.0
    environment:
      MYSQL_HOST: "mysql01"
      EUREKA_HOST: "erpfake-eureka"
      RABBITMQ_HOST: "rabbitmq"
    networks:
      - erpfake
networks:
  erpfake:
    external:
      name: erpfake-network